# serverless.yml

service: woowup-backend
plugins:
  - serverless-dotenv-plugin
  - serverless-offline 
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'